name: Social Readme

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: sun0225SUN/Social-Readme@main
        with:
          blog_rss_link: https://forimagine.eu.org/rss/feed.xml
          blog_limit: 5 # blog数量

          commit_message: Updated social rss by social-readme # commit说明
